### ISSUE TITLE
Accessing previous values of the SSAIntegrator

### ISSUE THREAD

**Issue by FerdinandGreiss** [SciML/DiffEqJump.jl#214]
Thanks for the amazing library! I am just playing with your SSAIntegrator and wanted to implement a DiscreteCallback that should be triggered when a value changes (du=-1). I get an error when I try to access to previous value with the `integrator.uprev` field (as suggested in https://github.com/SciML/DiffEqJump.jl/issues/78) and then verified that `uprev` is not defined in the SSAIntegrator. 

Could someone help me out. My example code is the following:

```
function condition(u, t, integrator)
    u[2] - integrator.uprev[2] < 0
end

function affect!(integrator)
    u = integrator.u
    u[4] = u[4] - 1 #Couple another quantity to u[2]
end

cb = DiscreteCallback(condition, affect!)
```

Thanks,
Ferdinand

**Comment by isaacsas** [comment]
The challenge here is going to be that saving `uprev` for many of the SSAs could actually be more (asymptotic) work per event than the SSA's underlying algorithm for finding and executing the event.

We can add a keyword to turn saving the previous state on, but it would need to be off by default. (The most efficient way for us to handle this would be just executing the same jump twice to update `u` and `uprev`, but we can't assume user `ConstantRateJump`s won't have internal state that give different results. So I don't think that is feasible to do currently.)

If you are using `SSAStepper`, since the callback condition is checked every timestep after executing the next jump, it might be fastest for you to make the condition a functor, in which you store the old value yourself. Maybe something like the following would work? (Note I haven't tested this.):
```julia
mutable struct UprevCondition{T}
     u2::T
end

function (upc::UprevCondition)(u, t, integrator)
    condit = u[2] - upc.u2 < 0
    upc.u2 = u[2]
    condit
end

function (upc::UprevCondition)(integrator)
    u = integrator.u
    u[4] = u[4] - 1 #Couple another quantity to u[2]
end

upc = UprevCondition(u0[2])
cb = DiscreteCallback(upc, upc)
```

**Comment by FerdinandGreiss** [comment]
Thanks! Worked nicely.

**Comment by isaacsas** [comment]
Cool, I’ll add an example like this to the FAQ then.

**Comment by isaacsas** [comment]
Example added in https://github.com/SciML/DiffEqJump.jl/pull/247
