### ISSUE TITLE
SSAIntegrator not playing nice with PresetTimeCallback -- ERROR: type SSAIntegrator has no field tdir

### ISSUE THREAD

**Issue by jae0** [SciML/DiffEqJump.jl#239]
Hi there. An expected field seems to be missing (tdir):  

`ERROR: type SSAIntegrator has no field tdir
Stacktrace:
  [1] getproperty
    @ ./Base.jl:42 [inlined]
  [2] (::DiffEqCallbacks.var"#62#65"{typeof(SciMLBase.INITIALIZE_DEFAULT), Bool, Vector{Float64}, typeof(affectpresets!)})(c::DiscreteCallback{DiffEqCallbacks.var"#60#63"{Vector{Float64}}, DiffEqCallbacks.var"#61#64"{typeof(affectpresets!)}, DiffEqCallbacks.var"#62#65"{typeof(SciMLBase.INITIALIZE_DEFAULT), Bool, Vector{Float64}, typeof(affectpresets!)},  ...
`

Minimal example to create the error follows:
`
using Catalyst, DifferentialEquations 

 rs = @reaction_network begin
   g, X --> 2X
   l, X --> 0
 end g l  

 dprob = DiscreteProblem(rs, [1000.0], (0.0, 100.0), ( 1.0, 1.0 ) )
 jprob = JumpProblem(rs, dprob, Direct(), save_positions=(false, false))
 cbtimes = [20.0, 30.0]
 affectpresets!(integrator) = integrator.u[1] += 1000
  
 jsol = solve(jprob, SSAStepper(), saveat=0.1, tstops=cbtimes, callback=PresetTimeCallback( cbtimes, affectpresets! )  )

`

**Comment by isaacsas** [comment]
Added a fix in https://github.com/SciML/DiffEqJump.jl/pull/240

A few notes on your code:
1. Don't use ` PresetTimeCallback` and manually set `tstops` in the `solve` call, or you'll end up with the `tstops` included twice. (i.e. the `PresetTimeCallback` already sets `tstops` for you.)
2. I'd recommend making your initial condition an integer vector instead of `Float64` unless you are trying to simulate a hybrid system that includes ODEs or SDEs for some components.

**Comment by jae0** [comment]
Great to hear. Thanks! And hats off to you. Jae
