### ISSUE TITLE
remake for JumpProblems

### ISSUE THREAD

**Issue by isaacsas** [SciML/DiffEqJump.jl#97]
Broken as described [here](https://discourse.julialang.org/t/controlling-save-behavior-and-performance-of-diffeqbiological/38387/5).

**Comment by isaacsas** [comment]
We need to double check what @gideonsimpson is doing doesn't mess up any SSAs. (i.e. whether there are components precalculated during `JumpProblem` construction that need to be reinitialized here, or whether that is properly handled in the initialization during the subsequent `solve` call).

**Comment by isaacsas** [comment]
See also:
https://github.com/SciML/DiffEqBiological.jl/issues/193

**Comment by gideonsimpson** [comment]
I just wanted to ask: Is it essential to the design of the module that problems need to be defined in two stages, first as a `DiscreteProblem` and then as a `JumpProblem`?  I know you guys want the flexibility to have the reaction network drive various types of dynamics, but could this be streamlined/

**Comment by ChrisRackauckas** [comment]
It probably could all be made into a callback though, but you'd still need to do `JumpCallback` and then `DiscreteProblem`. It's fundamental to the design because indeed, nothing ties jumps to `DiscreteProblem` or should tie it to that, because mixing them with ODEs and SDEs is definitely a useful thing to do.

**Comment by isaacsas** [comment]
Should be closed by https://github.com/SciML/DiffEqJump.jl/pull/164
